package com.example.ballzbeta.objects;

import java.util.List;

/**
 * Represents an order made between users in the warehouse system.
 */
public class Order {
    private int orderId;
    private String sender;      // UID of the sender
    private String receiver;    // UID of the receiver
    private String remark;
    private String dateTime;
    private boolean done;
    private boolean seen;
    private List<OrderItem> orderItemList;

    /**
     * Default constructor required for Firebase.
     */
    public Order() {}

    /**
     * Constructs an order.
     *
     * @param orderId       unique order identifier (usually 0 if generated by Firebase push)
     * @param sender        UID of the sending user
     * @param receiver      UID of the receiving user
     * @param remark        order notes
     * @param dateTime      creation and pickup timestamp
     * @param done          status flag
     * @param seen          read flag
     * @param orderItemList list of items in the order
     */
    public Order(int orderId, String sender, String receiver, String remark, String dateTime,
                 boolean done, boolean seen, List<OrderItem> orderItemList) {
        this.orderId = orderId;
        this.sender = sender;
        this.receiver = receiver;
        this.remark = remark;
        this.dateTime = dateTime;
        this.done = done;
        this.seen = seen;
        this.orderItemList = orderItemList;
    }

    // Getters and setters

    public int getOrderId() {
        return orderId;
    }

    public void setOrderId(int orderId) {
        this.orderId = orderId;
    }

    public String getSender() {
        return sender;
    }

    public void setSender(String sender) {
        this.sender = sender;
    }

    public String getReceiver() {
        return receiver;
    }

    public void setReceiver(String receiver) {
        this.receiver = receiver;
    }

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    public String getDateTime() {
        return dateTime;
    }

    public void setDateTime(String dateTime) {
        this.dateTime = dateTime;
    }

    public boolean isDone() {
        return done;
    }

    public void setDone(boolean done) {
        this.done = done;
    }

    public boolean isSeen() {
        return seen;
    }

    public void setSeen(boolean seen) {
        this.seen = seen;
    }

    public List<OrderItem> getOrderItemList() {
        return orderItemList;
    }

    public void setOrderItemList(List<OrderItem> orderItemList) {
        this.orderItemList = orderItemList;
    }
}
